#!/usr/bin/env python3
"""
CLI rename-search integration when tqdm is available.

Runs rename-search in a temp folder with a small set of files and checks that
the process completes and a report file is generated.
"""

from pathlib import Path
import shutil
import subprocess
import sys


def test_cli_rename_search_generates_report(tmp_path: Path):
    root = Path(__file__).parent.parent
    try:
        import tqdm  # type: ignore
    except Exception:
        import pytest
        pytest.skip("tqdm not available; skipping CLI rename-search test")

    # copy micro set of real-like PDFs
    src_dir = root / "tests" / "resources" / "real_pdfs"
    for p in src_dir.glob("*.pdf"):
        shutil.copy2(p, tmp_path / p.name)

    # run rename-search
    cli = root / "start_cli.py"
    res = subprocess.run(
        [sys.executable, str(cli), "rename-search", str(tmp_path)],
        capture_output=True,
        text=True,
        cwd=tmp_path,
        timeout=120,
    )
    assert res.returncode in (0, 1)
    # check that a default report may have been generated
    report = tmp_path / "book_metadata_report.json"
    assert report.exists(), "Expected a JSON report to be generated by rename-search"

